version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99997777
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  fatapi:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_container
    ports:
      - "8000:8000"
    command: ["/fastapi_app/docker/app.sh"]
    depends_on:
      - postgres