"""create token3

Revision ID: 28a5c40180fe
Revises: 7321dca518c5
Create Date: 2024-02-08 00:10:01.959824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a5c40180fe'
down_revision: Union[str, None] = '7321dca518c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.drop_column('token', 'user_id')
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'token', ['token'], ['access_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'token')
    op.add_column('token', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
