"""home2

Revision ID: 3bd1e4603471
Revises: df6439a349e6
Create Date: 2024-02-14 00:25:03.676398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd1e4603471'
down_revision: Union[str, None] = 'df6439a349e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('distance', sa.Float(), nullable=True))
    op.drop_column('question', 'distanse')
    op.add_column('route_rating', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.drop_constraint('route_rating_question_id_fkey', 'route_rating', type_='foreignkey')
    op.create_foreign_key(None, 'route_rating', 'survey', ['survey_id'], ['id'])
    op.drop_column('route_rating', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_rating', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route_rating', type_='foreignkey')
    op.create_foreign_key('route_rating_question_id_fkey', 'route_rating', 'question', ['question_id'], ['id'])
    op.drop_column('route_rating', 'survey_id')
    op.add_column('question', sa.Column('distanse', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('question', 'distance')
    # ### end Alembic commands ###
