"""user_response4

Revision ID: 4abc45c0aa63
Revises: fc078bdaa1f8
Create Date: 2024-02-13 17:41:27.065631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abc45c0aa63'
down_revision: Union[str, None] = 'fc078bdaa1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('distance', sa.Float(), nullable=True))
    op.drop_column('question', 'distanse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('distanse', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('question', 'distance')
    # ### end Alembic commands ###
