"""token4

Revision ID: 54d92d4cb7aa
Revises: 347770646f17
Create Date: 2024-02-19 15:58:58.180566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d92d4cb7aa'
down_revision: Union[str, None] = '347770646f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_code', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('password_reset_code', 'created_at ')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_code', sa.Column('created_at ', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('password_reset_code', 'created_at')
    # ### end Alembic commands ###
