"""image_question

Revision ID: 578e30a698b3
Revises: 8cc0878e082e
Create Date: 2024-02-20 14:01:58.294012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578e30a698b3'
down_revision: Union[str, None] = '8cc0878e082e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('survey', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('question', 'image_path')
    # ### end Alembic commands ###
