"""profile

Revision ID: 7907c3d59ac5
Revises: 61dfe5fd5f0e
Create Date: 2024-02-19 14:40:01.907909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7907c3d59ac5'
down_revision: Union[str, None] = '61dfe5fd5f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('os_version', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('app_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'app_version')
    op.drop_column('feedback', 'os_version')
    op.drop_column('feedback', 'device_name')
    # ### end Alembic commands ###
