"""questionnaire6

Revision ID: 8af23117aee2
Revises: 
Create Date: 2024-02-12 17:18:59.985744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af23117aee2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_response', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_response', type_='foreignkey')
    op.drop_column('user_response', 'user_id')
    # ### end Alembic commands ###
