"""image_survey

Revision ID: 8cc0878e082e
Revises: 87f2da718b8f
Create Date: 2024-02-20 13:34:05.868687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc0878e082e'
down_revision: Union[str, None] = '87f2da718b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'image_path')
    # ### end Alembic commands ###
