"""registration_13

Revision ID: 8dc7f7b5cc52
Revises: a7e69f4daf5c
Create Date: 2024-02-05 16:04:13.080787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc7f7b5cc52'
down_revision: Union[str, None] = 'a7e69f4daf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
