"""user_response2

Revision ID: 92302800d5ef
Revises: b800ea647a83
Create Date: 2024-02-13 17:32:47.406185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92302800d5ef'
down_revision: Union[str, None] = 'b800ea647a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_response_survey_id_fkey', 'user_response', type_='foreignkey')
    op.create_foreign_key(None, 'user_response', 'question', ['question_id'], ['id'])
    op.drop_column('user_response', 'survey_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response', sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_response', type_='foreignkey')
    op.create_foreign_key('user_response_survey_id_fkey', 'user_response', 'survey', ['survey_id'], ['id'])
    op.drop_column('user_response', 'question_id')
    # ### end Alembic commands ###
