"""create token4

Revision ID: 95cbf500819f
Revises: 28a5c40180fe
Create Date: 2024-02-08 00:17:22.892579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cbf500819f'
down_revision: Union[str, None] = '28a5c40180fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_token_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'token', ['token_id'], ['id'])
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_token_fkey', 'user', 'token', ['token'], ['access_token'])
    op.drop_column('user', 'token_id')
    # ### end Alembic commands ###
