"""home

Revision ID: ac448cc75e12
Revises: 
Create Date: 2024-02-13 22:56:09.549986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac448cc75e12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('title', sa.String(), nullable=True))
    op.add_column('question', sa.Column('description', sa.String(), nullable=True))
    op.add_column('question', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('question', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('distanse', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('time', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('question', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('question', 'rating')
    op.drop_column('question', 'price')
    op.drop_column('question', 'time')
    op.drop_column('question', 'distanse')
    op.drop_column('question', 'points')
    op.drop_column('question', 'short_description')
    op.drop_column('question', 'description')
    op.drop_column('question', 'title')
    op.drop_table('route_rating')
    # ### end Alembic commands ###
