"""home5

Revision ID: ac71dd5640c7
Revises: 7a5a5ef1a9ec
Create Date: 2024-02-12 21:06:19.633278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac71dd5640c7'
down_revision: Union[str, None] = '7a5a5ef1a9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_survey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_survey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], name='user_survey_survey_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_survey_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_survey_pkey')
    )
    op.drop_table('user_response')
    # ### end Alembic commands ###
