"""user_response5

Revision ID: e3d6e6bf6286
Revises: 4abc45c0aa63
Create Date: 2024-02-13 17:44:10.115632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d6e6bf6286'
down_revision: Union[str, None] = '4abc45c0aa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('distanse', sa.Float(), nullable=True))
    op.drop_column('question', 'distance')
    op.add_column('route_rating', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.drop_constraint('route_rating_question_id_fkey', 'route_rating', type_='foreignkey')
    op.create_foreign_key(None, 'route_rating', 'survey', ['survey_id'], ['id'])
    op.drop_column('route_rating', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_rating', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route_rating', type_='foreignkey')
    op.create_foreign_key('route_rating_question_id_fkey', 'route_rating', 'question', ['question_id'], ['id'])
    op.drop_column('route_rating', 'survey_id')
    op.add_column('question', sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('question', 'distanse')
    # ### end Alembic commands ###
