"""create token5

Revision ID: f06b4608cf31
Revises: 95cbf500819f
Create Date: 2024-02-08 00:21:46.968795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06b4608cf31'
down_revision: Union[str, None] = '95cbf500819f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_token_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_token_id_fkey', 'user', 'token', ['token_id'], ['id'])
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'user_id')
    # ### end Alembic commands ###
