"""fixUser2

Revision ID: f326f9f76595
Revises: 37151bef619c
Create Date: 2024-02-12 17:36:21.462659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f326f9f76595'
down_revision: Union[str, None] = '37151bef619c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_response_user_id_fkey', 'user_response', type_='foreignkey')
    op.drop_column('user_response', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_response_user_id_fkey', 'user_response', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
