"""user_response3

Revision ID: fc078bdaa1f8
Revises: 92302800d5ef
Create Date: 2024-02-13 17:34:06.448739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc078bdaa1f8'
down_revision: Union[str, None] = '92302800d5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_rating', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('route_rating_survey_id_fkey', 'route_rating', type_='foreignkey')
    op.create_foreign_key(None, 'route_rating', 'question', ['question_id'], ['id'])
    op.drop_column('route_rating', 'survey_id')
    op.add_column('user_response', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_response_question_id_fkey', 'user_response', type_='foreignkey')
    op.create_foreign_key(None, 'user_response', 'survey', ['survey_id'], ['id'])
    op.drop_column('user_response', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_response', type_='foreignkey')
    op.create_foreign_key('user_response_question_id_fkey', 'user_response', 'question', ['question_id'], ['id'])
    op.drop_column('user_response', 'survey_id')
    op.add_column('route_rating', sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route_rating', type_='foreignkey')
    op.create_foreign_key('route_rating_survey_id_fkey', 'route_rating', 'survey', ['survey_id'], ['id'])
    op.drop_column('route_rating', 'question_id')
    # ### end Alembic commands ###
